/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mn_mta_pos_exam_BridgePosAPI */

#ifndef _Included_mn_mta_pos_exam_BridgePosAPI
#define _Included_mn_mta_pos_exam_BridgePosAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mn_mta_pos_exam_BridgePosAPI
 * Method:    put
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mn_mta_pos_exam_BridgePosAPI_put
  (JNIEnv *, jclass, jstring);

/*
 * Class:     mn_mta_pos_exam_BridgePosAPI
 * Method:    returnBill
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mn_mta_pos_exam_BridgePosAPI_returnBill
  (JNIEnv *, jclass, jstring);

/*
 * Class:     mn_mta_pos_exam_BridgePosAPI
 * Method:    sendData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mn_mta_pos_exam_BridgePosAPI_sendData
  (JNIEnv *, jclass);

/*
 * Class:     mn_mta_pos_exam_BridgePosAPI
 * Method:    checkAPI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mn_mta_pos_exam_BridgePosAPI_checkAPI
  (JNIEnv *, jclass);

/*
 * Class:     mn_mta_pos_exam_BridgePosAPI
 * Method:    getInformation
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mn_mta_pos_exam_BridgePosAPI_getInformation
  (JNIEnv *, jclass);

/*
 * Class:     mn_mta_pos_exam_BridgePosAPI
 * Method:    callFunction
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mn_mta_pos_exam_BridgePosAPI_callFunction
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
